[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x86-64-simple-os.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"
